### ISSUE TITLE
Simulations not running on Firefox

### ISSUE THREAD

**Issue by XianMaeve** [visua0/Melvor-Idle-Combat-Simulator-Reloaded#103] opened 2022-08-26 23:50 UTC
![firefox_hYjFtNsqya](https://user-images.githubusercontent.com/70384490/187004687-938b9bff-c2cb-4631-857f-b3f212709052.png)
![firefox_iwHESqubSy](https://user-images.githubusercontent.com/70384490/187004691-0be7424c-40be-4391-a51d-16187f39e798.png)

Attached are screenshots from error in console

I run SEMI and a few userscripts, but the error still happens with only combat simulator installed.

Simulator hangs on 0/x whenever trying to simulate, and on canceling... after canceling.

**Comment by saltyeyes** [comment] 2022-09-01 03:15
I just had a similar issue, which was caused by the default CSP not liking the use of `eval()`. Can you try downloading the latest release and adding the following to manifest.json, see if that fixes the problem for you?
`"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self';"`

**Comment by gmiclotte** [comment] 2022-09-01 07:54
Oh joy, and here I thought the firefox-hates-eval saga would finally be over.

Should be fixed if you update to the most recent version (v1.7.0) on AMO.
Thanks for providing the fix @saltyeyes 

Note that while the most recent version is v1.7.0, it incorrectly shows v1.6.10 in game.

**Closed** 2022-09-02 12:37 UTC
